/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mjiayou_trecore_test_jni_TestJNIUtil */

#ifndef _Included_com_mjiayou_trecore_test_jni_TestJNIUtil
#define _Included_com_mjiayou_trecore_test_jni_TestJNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mjiayou_trecore_test_jni_TestJNIUtil
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mjiayou_trecore_test_jni_TestJNIUtil_getHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
